---
security:
  oauth2:
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: 
      userAuthorizationUri: 
      tokenName: 
      authenticationScheme:
      clientAuthenticationScheme:
    resource:
      userInfoUri:

spring:
  main:
    allow-bean-definition-overriding: true